module.exports = {
  defaultBuildType: 'productionExecutable',
  gradleBuildArgs: ':h5App:jsDevelopmentExecutableCompileSync :demo:packLocalJSBundleDebug -Pkuikly.useLocalKsp=false -Pkuikly.coverageBuild=true',
  processedResourcesDir: 'h5App/build/processedResources/js/main',
  demoDistBaseDir: 'demo/build/dist/js',
  developmentDistSubdir: 'developmentExecutable',
  kotlinWebpackDir: 'h5App/build/kotlin-webpack/js/developmentExecutable',
  kotlinModulesDir: 'h5App/build/compileSync/js/main/developmentExecutable/kotlin',
  whistleHtdocsDir: 'node_modules/whistle/biz/webui/htdocs',
  instrumentedDirName: 'instrumented',
  instrumentedModulesDirName: 'modules',
  composeResourcesDirName: 'composeResources',
  fontsDirName: 'fonts',
  fontFileName: 'NotoSansSC-Regular.woff2',
  indexHtmlRelativePath: 'h5App/build/processedResources/js/main/index.html',
  nativeVueRemoteUrl: 'http://127.0.0.1:8083/nativevue2.js',
  nativeVueLocalFileName: 'nativevue2.js',
};
